### ISSUE TITLE
Missing PDB files for AngelScript, MariaDB for Debug and MariaDB library conflict for both

### ISSUE THREAD

**Issue by JoelTroch** [SamVanheer/HLEnhanced#18]
VS2015 complains on a clean build on Debug with everything enabled (AngelScript + SQL + OpFor) that PDB files for AngelScript and MariaDB are missing (LNK4999) in the "cl_dll/dlls" directories.

Example:
`mariadbclient.lib(array.obj) : warning LNK4099: PDB 'mariadb_obj.pdb' n'a pu être trouvé avec 'mariadbclient.lib(array.obj)' ou sur 'C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hlenhanced\dlls\mariadb_obj.pdb' ; l'objet sera lié sans informations de débogage`

Also it seems that there is a conflict with MariaDB library:

`LINK : warning LNK4098: conflit entre la bibliothèque par défaut 'LIBCMT' et les autres bibliothèques ; utilisez /NODEFAULTLIB:library
LINK : warning LNK4199: /DELAYLOAD:libmariadb.dll ignoré ; aucune importation trouvée à partir de libmariadb.dll`

The "delayload" warning also happen in "Release" configuration.

**Comment by SamVanheer** [comment]
I can't find mariadb_obj.pdb anywhere, seems like i'll have to compile it myself to get that.

The default library issues are caused by some libraries using the release C runtime, while others use the debug runtime. I'll have to make it use debug libraries instead to match the runtimes. Not sure if that's easy to do though.

The delayload issue is odd since it does use exported symbols. SQLite does the same thing and doesn't cause any errors.

**Comment by JoelTroch** [comment]
Closing this (yes after a year) since you need to build MariaDB yourself.
