### ISSUE TITLE
CWeaponInfo/CHudAmmo related crashes on Xash3D

### ISSUE THREAD

**Issue by fgsfdsfgs** [SamVanheer/HLEnhanced#23]
First, I know that it's stated in the wiki that HLEnhanced "won't work" on Xash3D and thus it's probably not a really good idea to post this here.

I decided to try and run HLE on the latest fork/version of Xash, because it has VGUI support and can run the latest Steam version of HL1 with no problems or changes to the game libs. I tested various versions and here's what I found:
- an old version that's in the first post of the TWHL thread works pretty much flawlessly, at least I was't able to crash it;
- latest prebuilt version from the game repository crashes on entering the main menu, not sure where exactly, since I don't have debug symbols for that;
- the current HEAD compiled with VS2015 works, but it crashes as soon as you pick up/spawn with a weapon. Crashes happen at seemingly random points of CHudAmmo.cpp because of invalid pointer accesses, with the invalid pointer usually being "this" of a CWeaponInfo instance, most often in CWeaponInfo::GetPrimaryAmmo.

I also noticed that g_pFileSystem stuff fails to open/read files, so I assumed that the crash happens because no weapon info scripts can be loaded. I replaced those segments with some code that uses COM_LoadFile and the scripts did load successfully, however that did not remove the crashes.
Server seems to work alright, since running it in dedicated server mode doesn't cause any crashes. It's not of much use though, since the client crashes upon entering any map where you spawn with weapons.

Any ideas on what I could do to make it not crash? I understand if you don't want to/can't answer this question, in that case just delete this and I'll try to solve it myself.

**Comment by SamVanheer** [comment]
It might be crashing because ammo types aren't being loaded correctly. I'll have to make it use default ammo data for unspecified ammo types so it's never a null pointer. Weapons will have infinite ammo, but at least it'll run. Weapon data itself should already be non-null if it fails to load, since it returns a dummy instance instead.

If it still crashes i'll have to debug it. Where can i get the latest Xash3D build?

**Comment by FGSFDSFGS** [comment]
Thanks for the reply. You can get the latest binary release from their [GitHub repo](https://github.com/FWGS/xash3d/releases/tag/0.18.1). I used the latest revision, which I built with VS2015, though, but I don't think there have been any significant changes since 0.18.1.

**Comment by SamVanheer** [comment]
I've set default weapon HUD info for the default weapon info object so clients won't crash. It won't allow you to select weapons or shoot anything, but it's better than crashing.

Regarding the filesystem failing to load stuff: the engine sets up search paths for the filesystem, so under Xash the filesystem won't have any search paths set. 
If you can detect Xash's presence then you can manually set up the filesystem. I'll have to write that code anyway for the engine, so once that's done it can be used by HLE as well just in case it's needed.

**Comment by FGSFDSFGS** [comment]
Thanks.
I tried adding search paths manually and it worked: weapon scripts, AS scripts and material lists do load, or at least the console messages do print. Plugins also seem to run. However, it still crashes in almost the same spot.
First, as it turns out, Xash calls CHudAmmo methods while in the main menu for some reason, and during that time g_Prediction.GetLocalPlayer() returns NULL. I fixed that with simple NULL checks in CHudAmmo.cpp, and was able to load a map with no problem. Upon picking up a weapon though it crashed again, this time with this error (Xash includes a simple stack trace printer in case it dies):
![Error](http://i.imgur.com/PsY5kv2.png)
It appears that in UpdateWeaponHUD() pWeapon is actually NULL, as checking for that removes the crash, and the weapon functions properly, although it doesn't play any animations, effects or sounds or display its ammo count on the HUD.
I don't even know what could be the cause of this.

**Comment by SamVanheer** [comment]
Xash shouldn't be calling the HUD if there is no active map, unless it's running a background map. In that case, GetLocalPlayer should be returning a valid instance so it's a problem on their end.

UpdateWeaponHUD is called in only 2 locations, one of them could have a possible race condition so i've added a null pointer check there.

If the game fails to load weapon info it won't be able to handle the weapon's logic properly. Ammo counts, reloading and firing the weapon all depend on valid ammo data and HUD sprites, so if those failed to load, it'll break. It should be playing animations though, that's not supposed to be affected by missing weapon info.

test_func_vehicle depends very recent changes being included, so if you haven't updated yet it'll fail to spawn it.

I don't know why test_camera_angles would crash the game, if you could provide some more information that would be great.

test_camera_notinpvs is supposed to illustrate a bug in the engine that's preventing the camera from rendering anything outside the PVS. I reported this issue here: https://github.com/ValveSoftware/halflife/issues/1745
I'm sure Xash's code has a similar problem. I took a quick look around and found no references to cl.refdef.viewentity in the rendering code, which should be using that entity to determine where the player is looking from.

**Comment by FGSFDSFGS** [comment]
I saw your commit with the check just now, and that's basically what I did.
I don't know if it actually loads the weapon info properly, but there's no error messages in the console, only the "LoadWeaponInfoFromFile: Opened file..." ones. Is there anything I could do to check that?
As for test_camera_angles, turns out that it only crashes if I change to it from test_custom_entities. Doesn't seem to crash when I change to it from any other map. Here's the stack trace:
![Error](http://i.imgur.com/G93DOrc.png)

**Comment by SamVanheer** [comment]
That's because the custom entity code is calling into CBaseEntity in the destructor. The CBaseEntity instance is already freed at that point. I have to update the script to stop calling that. I encountered that problem myself earlier today, but i've been doing some other stuff so i hadn't gotten to it yet.

**Comment by FGSFDSFGS** [comment]
Okay then.
As for the weapon thing, the fire rates are correct for all weapons, projectile weapons seem to shoot their projectiles correctly and all the guns do reload, but hitscan weapons don't actually seem to produce tracers or bullet hole decals, all weapons are missing their animations and stuff like muzzle flashes, weapon_egon and weapon_gauss don't spawn the beams and there's no ammo counter. I suspect this might be a problem with Xash that I've already encountered, I'll check for that.

**Comment by fuzun** [comment]
You should try Uncle mike's legacy xash3d. It was at their base but I could not find it now.

**Comment by SamVanheer** [comment]
It's accessing the primary ammo data, which is null if it didn't load it from the file. That means it's probably using the default weapon info object, or it's failing to load the ammo types from it somehow. Add some alerts and see if you can find where it's failing.

**Comment by FGSFDSFGS** [comment]
The info files load fine on both sides, but it looks like at some point the pointer to weapon info inside the weapon object returned by g_Prediction.GetWeapon() on the client becomes invalid, because the crashes seem to happen when the HUD tries to access one of the weapon info fields (like GetPrimaryAmmo or GetHUDInfo), and the pointer itself is not null. I might be wrong, though.

**Comment by SamVanheer** [comment]
I tried to launch HLE under Xash, but it fails to locate client.dll. I'm using the Custom Game menu, HLEnhanced is in a directory called hlenhanced in the main Xash3D directory. I checked its source code, but i don't see any reason why it should be failing to load it. Is there anything that i'm missing?

**Comment by FGSFDSFGS** [comment]
It's actually locating it, but it's failing to load because for whatever reason it assumes that filesystem_stdio.dll is in the mod directory and not in the root directory. hl.dll, on the other hand, assumes root directory. I just copied it into the mod directory.
There might be more DLL-related errors, but I don't recall exactly which I have encountered while setting it up. If you aren't already, try running it with "-dev 5". That enables a separate console window and enables all log messages.

**Comment by a1batross** [comment]
Xash don't support Valve's FileSystem_Stdio, so there is no way to load any dll that uses it. Uncle Mike's Xash3D build 3598 also now support newer VGUI1 dll, as it was done in forked Xash3D.

**Comment by JoelTroch** [comment]
@a1batross Is it possible to write a sort of "wrapper" that handle Valve's FileSystem_Stdio <-> Xash3D conversion or we'll have to make a fork dedicated to Xash3D if we want to support it?

**Comment by a1batross** [comment]
I plan to support FS_Stdio in libVInterface for Xash3D FWGS fork. When I
will have free time for it. :)

23 янв. 2017 г. 4:08 PM пользователь "Joël Troch" <notifications@github.com>
написал:

**Comment by SamVanheer** [comment]
I can add a wrapper that implements IFileSystem and calls into that interface, provided it has the same features. Otherwise i can add in the filesystem from the prototype engine, which can replace filesystem_stdio.

**Comment by SamVanheer** [comment]
Xash is not supported by HLEnhanced.
