### ISSUE TITLE
Project files teir1 and vgui_controls could not be found (VS2013)

### ISSUE THREAD

**Issue by CrusoeDaWolf** [SamVanheer/HLEnhanced#3]
Not sure if it's a problem with the source or VS itself. VS2013 can't seem to find project files for teir1 and vgui_controls :c

Also, do the compiled binaries work with Xash3D?

**Comment by SamVanheer** [comment]
Those projects are currently not included, since both are Source SDK projects. There may be legal issues involved with using them in non-Source engine mod projects, which is why they're not included.

As far as i know, this will not work with Xash3D. Since i'm referencing VGUI2 code, which Xash probably doesn't support, it won't work. Unless Xash supports that as well, you'll have trouble with it. I'll look into making VGUI2 support optional, but i can't promise anything.

Also, you'll have problems compiling in any compiler that doesn't support C++14, since some of its features are being used. You'll need VS2015.

**Comment by CrusoeDaWolf** [comment]
Alright. Thanks!

**Comment by JoelTroch** [comment]
@CrusoeDaWolf Linux/OS X Makefiles won't work because it's still based on the GitHub Makefiles.

I prefer to wait that @SamVanheer convert everything to CMake before keeping working on Linux / OS X.

**Comment by SamVanheer** [comment]
I've written CMakeLists and disabled VGUI2, so you should be able to compile the game yourself now on both Windows and Linux.

**Comment by JoelTroch** [comment]
I think this issue can be closed due to the switch to CMake.

**Comment by CrusoeDaWolf** [comment]
I was able to compile with no problem. Closing now.
