### ISSUE TITLE
[Windows / VS2015] Projects files out of sync

### ISSUE THREAD

**Issue by JoelTroch** [SamVanheer/HLEnhanced#4]
Using VS2015 Pro Update 3 with repo at commit: https://github.com/SamVanheer/HLEnhanced/commit/8ccd76a305ae259cbc0e711d47d841e98751761d

* Impossible to open a lot of files related to client HUD stuff (**saytext.cpp, text_message.cpp**)
* Impossible to open **CBasePlayerItem.server.cpp** and **CBasePlayerItem.client.cpp**
* Impossible to open some AngelScript related files (**ASCBaseEntity.cpp, CASEngine.cpp and ASCGlobalVars.cpp**)

This prevent the compilation of the client and server projects.

**Comment by SamVanheer** [comment]
Are you still using the old project files? Only the CMake version is up-to-date, the old ones in projects/ are no longer kept up to date. I'm only keeping them until i'm sure all settings have been added to the CMake version. Files like saytext.cpp have been renamed since then, so you shouldn't be able to open those at all.

**Comment by JoelTroch** [comment]
I was using old projects files, gonna test with CMake.

**Comment by JoelTroch** [comment]
Errors are gone with CMake. Issue is resolved.
