### ISSUE TITLE
DelayedUse is wrongly passing on its internal temporary entity

### ISSUE THREAD

**Issue by Xalalau** [SamVanheer/HLEnhanced#41]
This bug kills the multisource entity and then it kills the teleport at beginning of the c1a0c level. 

Here is my ugly workaround: https://github.com/xalalau/H3LEnhanced/commit/9547db612622b058698ab39cac628ab4c5ed65fd

Just ignore the Portuguese...

**Comment by SamVanheer** [comment]
This code is identical to the SDK version, so Half-Life would also be affected by this.

The actual cause is that multisource had a bug that was fixed. In the original version, even if an entity wasn't in the list of targets it would still accept the input.

The bug is reported here: https://github.com/ValveSoftware/halflife/issues/1737

A better solution would indeed be to use the original caller. That retains the original behavior without keeping multisource as buggy as it is in the SDK, and matches the behavior of Source's I/O system.

**Comment by SamVanheer** [comment]
I've modified your solution to account for 2 things:
* You were always passing the chain entity even if it wasn't a delayed trigger. I see you modified your code later on to account for this
* The original caller is save/restored so it isn't lost during transitions or when loading saved games
